config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/tasks", to: "tasks#index"
  get "/tasks/new", to: "tasks#new", as: :create 
  get "/tasks/edit/:id", to: "tasks#edit", as: :edit 
  get "/tasks/:id", to: "tasks#show", as: :task 
  post "/tasks", to: "tasks#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @tasks = Task.all 
    end 

    def show
        @task = Task.find(params[:id]) 
    end

    def new
        @task = Task.new
    end 

    def create
        @task = Task.new(task_params)
        @task.save

        redirect_to task_path(@task)
    end 

    def update
        @restaurant = Restaurant.find(params[:id])
        @restaurant.update(restaurant_params)

        redirect_to task_path(@task) 
      end 

    private

    def task_params
        # *Strong params*: You need to *whitelist* what can be updated by the user
        # Never trust user data!
        params.require(:task).permit(:title, :details, :completed)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
 
<div>
    <%= f.label :title %>
    <%= f.text_field :title %>
</div>


  <div>
        <%= f.label :details %>
        <%= f.text_field :details %>
  </div>

  <div>
      <%= f.label :completed %>
      <%= f.check_box :completed %>
  </div>
  
<div>
  <%= f.submit %>
</div>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<div class="checkboxes">
<% @tasks.each do |task| %> 
    <p>
    <input type="checkbox" <%= "checked = 'checked'" if task.completed%> >
    <%= link_to task.title, task %>
    </p>
<% end  %>

<%= link_to "Add new element", create_path  %>  
</div>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
 
<div>
    <%= f.label :title %>
    <%= f.text_field :title %>
</div>


  <div>
        <%= f.label :details %>
        <%= f.text_field :details %>
  </div>
  
<div>
  <%= f.submit %>
</div>
<% end %>

app/views/tasks/show.html.erb
<div>
    <h1>
        <%= @task.title %>
    </h1>
</div>
<div>
    <p>
            <%= @task.details %>
    </p>
</div>
<div>
<%= @task.completed %>
</div>

<%= link_to "Back to list", tasks_path  %> 
<%= link_to "Edit", edit_path  %> 